server:
  port: 8085
  error:
    whitelabel:
      enabled: false

spring:
  config:
    import: optional:file:.env[.properties]
  security:
    oauth2:
      client:
        registration:
          tuurio:
            client-id: ${TUURIO_CLIENT_ID:php-KQD8}
            client-secret: ${TUURIO_CLIENT_SECRET:YOUR_CLIENT_SECRET}
            scope: ${TUURIO_SCOPE:openid,profile,email}
            authorization-grant-type: authorization_code
            redirect-uri: ${TUURIO_REDIRECT_URI:{baseUrl}/auth/callback}
        provider:
          tuurio:
            issuer-uri: ${TUURIO_ISSUER:https://test.id.tuurio.com}
            user-name-attribute: sub
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: true
