server:
  port: 8085
  error:
    whitelabel:
      enabled: false

spring:
  security:
    oauth2:
      client:
        registration:
          tuurio:
            client-id: php-KQD8
            client-secret: YOUR_CLIENT_SECRET
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/auth/callback"
        provider:
          tuurio:
            issuer-uri: https://test.id.tuurio.com
            user-name-attribute: sub
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: true
